import state from './state'
import actions from './actions'
import mutations from './mutations'
import getters from './getters'
import config from './modules/config'
import user from './modules/user'
